### ISSUE TITLE
Escrever mais tests

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/talkshow#10]
Adicionar `coverage` e escrever mais testes

**Comment by tiagovizoto** [comment]
Ae bruno, peguei essa issue. Já estou escrevendo os testes <3

**Comment by rochacbruno** [comment]
@tiagovizoto blza, lembre-se de fazer na branch `extended` e veja se cosnegue adicionar o pytest-cov e codecov

**Comment by tiagovizoto** [comment]
Nem sei o que é isso. Mas irei estudar essas duas libs que tu citou. :) 
Farei bem bacana
