### ISSUE TITLE
Serialização de datetime

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/talkshow#11]
Atualmente a data do evento e da submissão de proposta estão em plain text

implementar o `tinydb_serialization` https://github.com/schapman1974/tinymongo#handling-datetime-objects

**Comment by viniciusfk9** [comment]
Oi @rochacbruno poderia falar um pouco mais sobre essa issue? 
Para criação do evento, a data é enviada como string em um formato como '%Y-%m-%d' para fazer parse para um `datetime` e assim salvar como um `datetime` no db? Se for realmente isso, eu mando o PR que está implementado. 
Valeu!

**Comment by rochacbruno** [comment]
Olá @viniciusfk9 o tinymongo possui um serializador de Datetime. https://github.com/schapman1974/tinymongo#handling-datetime-objects

Seria algo como

```python
from tinydb_serialization import SerializationMiddleware
from tinymongo import TinyMongoClient as BaseTinyMongoClient
from tinymongo.serializers import DateTimeSerializer

class TinyMongoClient(BaseTinyMongoClient):
    @property
    def _storage(self):
        serialization = SerializationMiddleware()
        serialization.register_serializer(DateTimeSerializer(), 'TinyDate')
        return serialization
```

e então usar neste linha https://github.com/rochacbruno/talkshow/blob/extended/talkshow/ext/db.py#L11

Alterar nos comandos e testes para usar o formato de data correto.

**Comment by viniciusfk9** [comment]
Ok, era isso mesmo. Mandarei o PR!
