### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/talkshow#2]
HAbilitar travis CI, criar .travis.yml e configurar para rodar os testes

**Comment by Riverfount** [comment]
@rochacbruno tem um repo do projeto junto ao Travis CI para utilizarmos?

**Comment by rochacbruno** [comment]
Tem sim! https://travis-ci.com/rochacbruno/talkshow

Só precisa criar o `.travis.yml`

```
language: python
python:
  - "3.6"
install:
  - "python setup.py install"
  - "pip install flake8"
script:
  - "flake8 talkshow/"
  - "flake8 tests/"
  - "py.test -v tests/"
```
