### ISSUE TITLE
alterar event route para receber slug ao inves do id

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/talkshow#8]
Usar `awesome-slugify` para criar o slug ao salvar o evento e então aceitar o slug na hora de fazer a query em https://github.com/rochacbruno/talkshow/blob/master/talkshow/blueprints/webui.py#L38 

ao inves de `/23495873498573498753498` usaremos `/flask-conf-2018` para acessar os detalhes do evento e o form.

**Comment by rochacbruno** [comment]
@chicobentojr lembrando que modificações estão sendo feitas na branch `extended` https://github.com/rochacbruno/talkshow/tree/extended

**Comment by neiesc** [comment]
@chicobentojr já acabei de implementar falta só abrir o PR.
